### ISSUE TITLE
Broken scripts after package changes in terraform-provider-aws

### ISSUE THREAD

**Issue by giograno** [localstack/localstack-terraform-test#11]
When this pipeline has been written, all the tests were located in the `aws` package. 
Later, the [terraform-provider-aws](https://github.com/hashicorp/terraform-provider-aws) changed this package structure, breaking our scripts.
At the moment, each service has tests located in a distinct package, specifically under `internal/service/<service>`.
Our script was designed to compile a single test executable with:
https://github.com/localstack/localstack-terraform-test/blob/a4194078d2905d33ce22997abd85924ab98c414b/bin/install-aws-test#L36
At the moment, we would need to generate multiple executable, one for each service, since the `-c` flag cannot be used with multiple packages (a [proposal](https://github.com/golang/go/issues/15513) for this feature has been accepted though).

**Comment by macnev2013** [comment]
Hey @giograno, Thanks for reporting. It has been fixed in the latest version. Please let me know if the issue still persists.
